require "test_helper"

module FlowChat
  module Whatsapp
    module Middleware
      class ChoiceMapperTest < Minitest::Test
        def setup
          @app = Minitest::Mock.new
          @middleware = ChoiceMapper.new(@app)
          @session = MockSession.new
          @context = MockContext.new(@session)
        end

        # The bug this whole redesign came from. The id was generated by
        # normalizing the label, which stripped "!", so choice "a" was given
        # the id "Yes" - choice "b"'s label exactly - and the id map was
        # consulted before the alias map. A user typing what was printed on
        # button b landed on a.
        def test_typing_a_title_resolves_to_the_choice_that_shows_it
          choices = {"a" => "Yes!", "b" => "Yes"}
          @app.expect :call, [:text, "response", choices, nil], [@context]
          @middleware.call(@context)

          @context.input = "Yes"
          @app.expect :call, [:text, "response", nil, nil], [@context]
          @middleware.call(@context)

          assert_equal "b", @context.input, "typing what button b shows must resolve to b"
        end

        def test_typing_the_other_title_still_resolves_to_its_own_choice
          choices = {"a" => "Yes!", "b" => "Yes"}
          @app.expect :call, [:text, "response", choices, nil], [@context]
          @middleware.call(@context)

          @context.input = "Yes!"
          @app.expect :call, [:text, "response", nil, nil], [@context]
          @middleware.call(@context)

          assert_equal "a", @context.input
        end

        # Two choices sharing a label are numbered, which is what makes the
        # wire values distinct - there is no generated suffix any more.
        def test_duplicate_labels_are_numbered_and_both_resolve
          choices = {"a" => "Savings", "b" => "Savings"}
          @app.expect :call, [:text, "response", choices, nil], [@context]
          rendered = @middleware.call(@context)[2]

          assert_equal ["1. Savings", "2. Savings"], rendered.keys

          @context.input = "2. Savings"
          @app.expect :call, [:text, "response", nil, nil], [@context]
          @middleware.call(@context)

          assert_equal "b", @context.input
        end

        def test_no_alias_mapping_is_written
          choices = {"a" => "Yes", "b" => "No"}
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          assert_nil @session.get("whatsapp.alias_mapping")
        end

        # WhatsApp caps a list row id at 200 characters and a button id at
        # 256. Ids used to be generated from the full label and could exceed
        # both; a title is bounded by the rung's own cap instead.
        def test_wire_values_stay_inside_the_platform_id_caps
          choices = (1..8).to_h { |i| ["k#{i}", "#{"a very long option label " * 20}#{i}"] }
          @app.expect :call, [:text, "response", choices, nil], [@context]

          rendered = @middleware.call(@context)[2]

          rendered.keys.each do |wire_value|
            assert_operator wire_value.length, :<=, 200, "list row id cap is 200 characters"
          end
        end

        def test_no_interception_without_mapping
          @context.input = "some_input"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          result = @middleware.call(@context)

          assert_equal "some_input", @context.input
          assert_equal [:text, "response", nil, nil], result
          @app.verify
        end

        def test_no_interception_with_blank_input
          @session.set("whatsapp.choice_mapping", {"accept" => "original_accept"})
          @context.input = nil
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_nil @context.input
          @app.verify
        end

        def test_intercepts_and_maps_choice
          mapping = {"create_account" => "create", "login" => "login"}
          @session.set("whatsapp.choice_mapping", mapping)
          @context.input = "create_account"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "create", @context.input
          @app.verify
        end

        def test_intercepts_duplicate_with_hash
          mapping = {
            "accept" => "accept_option_1",
            "accept_a1b2c3" => "accept_option_2"
          }
          @session.set("whatsapp.choice_mapping", mapping)
          @context.input = "accept_a1b2c3"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "accept_option_2", @context.input
          @app.verify
        end

        def test_passes_through_unmapped_input
          mapping = {"accept" => "original_accept"}
          @session.set("whatsapp.choice_mapping", mapping)
          @context.input = "free_text_response"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "free_text_response", @context.input
          @app.verify
        end

        def test_creates_mapping_from_choices
          # Middleware receives choices from app and creates mapping
          choices = {"create" => "Create Account", "login" => "Login"}
          @app.expect :call, [:text, "response", choices, nil], [@context]

          _, _, transformed_choices, _ = @middleware.call(@context)

          # Middleware should transform choices to use generated IDs as keys
          assert_equal "Create Account", transformed_choices["Create Account"]
          assert_equal "Login", transformed_choices["Login"]

          # Middleware should store mapping: generated_id => original_key
          mapping = @session.get("whatsapp.choice_mapping")
          assert_equal "create", mapping["Create Account"]
          assert_equal "login", mapping["Login"]
          @app.verify
        end

        def test_clears_mapping_on_blank_input
          mapping = {"accept" => "original_accept"}
          @session.set("whatsapp.choice_mapping", mapping)
          @context.input = nil
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_nil @session.get("whatsapp.choice_mapping")
          @app.verify
        end

        def test_clears_mapping_when_input_doesnt_match
          mapping = {"accept" => "original_accept"}
          @session.set("whatsapp.choice_mapping", mapping)
          @context.input = "unrelated_input"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          # Mapping should be cleared before app.call
          assert_nil @session.get("whatsapp.choice_mapping")
          @app.verify
        end

        def test_clears_mapping_after_successful_match
          mapping = {"accept" => "original_accept", "decline" => "original_decline"}
          @session.set("whatsapp.choice_mapping", mapping)
          @context.input = "accept"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          # Input should be mapped
          assert_equal "original_accept", @context.input

          # Mapping should be cleared after successful match (like USSD does)
          assert_nil @session.get("whatsapp.choice_mapping")
          @app.verify
        end

        def test_replaces_old_mapping_with_new
          # Old mapping exists in session
          old_mapping = {"old_button" => "old_choice"}
          @session.set("whatsapp.choice_mapping", old_mapping)

          # App returns new choices
          new_choices = {"new_option" => "New Choice"}
          @app.expect :call, [:text, "response", new_choices, nil], [@context]

          @middleware.call(@context)

          # New mapping should replace old
          mapping = @session.get("whatsapp.choice_mapping")
          assert_equal "new_option", mapping["New Choice"]
          @app.verify
        end

        def test_multiple_sequential_mappings
          # First interaction - app returns choices
          choices1 = {"choice1" => "Button 1"}
          @app.expect :call, [:text, "response1", choices1, nil], [@context]
          @middleware.call(@context)

          # Verify mapping was stored
          mapping = @session.get("whatsapp.choice_mapping")
          assert_equal "choice1", mapping["Button 1"]

          # Second interaction - user responds with generated ID
          @context.input = "Button 1"
          @app.expect :call, [:text, "response2", nil, nil], [@context]
          @middleware.call(@context)

          # Input should be mapped back to original key
          assert_equal "choice1", @context.input
          @app.verify
        end

        def test_empty_mapping_hash_is_treated_as_no_mapping
          @session.set("whatsapp.choice_mapping", {})
          @context.input = "some_input"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "some_input", @context.input
          @app.verify
        end

        def test_typed_number_resolves_on_the_numbered_rung
          choices = (1..25).to_h { |i| ["key#{i}", "Option #{i}"] }
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          @context.input = "3"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "key3", @context.input
          @app.verify
        end

        # No number is on screen for a short, unique set of titles, so a
        # typed digit here is free text, not a position: there is nothing
        # for the position map to resolve, and storing one anyway would let
        # a coincidental digit hijack a reply it was never meant to.
        def test_no_position_map_on_an_unambiguous_button_rung
          choices = {"a" => "Alpha", "b" => "Beta"}
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          assert_nil @session.get("whatsapp.position_mapping")
          @app.verify
        end

        def test_no_position_map_on_an_unambiguous_list_rung
          choices = (1..5).to_h { |i| ["key#{i}", "Option #{i}"] }
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          assert_nil @session.get("whatsapp.position_mapping")
          @app.verify
        end

        # Contrast with the two tests above: FlowChat::ChoiceTitles.ambiguous?
        # decides a set needs numbering, so the position map is stored for
        # it, on the same button/list rungs that have none when unambiguous.
        def test_position_map_exists_on_an_ambiguous_button_rung
          choices = {"a" => "Accept", "b" => "Accept"}
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          assert_equal "a", @session.get("whatsapp.position_mapping")["1"]
          assert_equal "b", @session.get("whatsapp.position_mapping")["2"]
          @app.verify
        end

        def test_position_map_exists_on_an_ambiguous_list_rung
          long_label = "A label that is definitely longer than twenty-four chars"
          choices = {"a" => long_label}.merge((2..4).to_h { |i| ["k#{i}", "Option #{i}"] })
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          assert_equal "a", @session.get("whatsapp.position_mapping")["1"]
          @app.verify
        end

        # A title and a stored position occupy the same key space: a choice
        # labelled "5" has the title "5", the same string as the position of
        # the 5th choice. Titles must win, or that choice is unreachable -
        # get_choice_mapping is consulted before get_position_mapping.
        def test_a_label_that_reads_as_a_position_resolves_to_its_own_choice
          choices = {"k1" => "5"}.merge((2..11).to_h { |i| ["k#{i}", "Option #{i}"] })
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          @context.input = "5"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "k1", @context.input, "the id for the label \"5\" must win over position 5"
        end

        # The renderer prefixes a button title with its position and
        # truncates to 20 chars, so a user who types exactly what they see
        # (rather than the full, unprefixed label the id was generated from)
        # must still resolve.
        def test_typed_truncated_button_title_resolves
          long_label = "A label that is definitely longer than twenty chars"
          choices = {"a" => long_label, "b" => "Beta"}
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          @context.input = "1. A label that i..." # 20 chars, as WhatsApp renders it on a button
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "a", @context.input
          @app.verify
        end

        # Above 3 choices WhatsApp renders a list instead of buttons, with a
        # 24 char row title cap instead of 20.
        def test_typed_truncated_list_row_title_resolves
          long_label = "A label that is definitely longer than twenty-four chars"
          choices = {"a" => long_label}.merge((2..4).to_h { |i| ["k#{i}", "Option #{i}"] })
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          @context.input = "1. A label that is de..." # 24 chars, as WhatsApp renders it in a list row
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "a", @context.input
          @app.verify
        end

        # a1d08a4 could alias neither of these labels, because both truncate
        # to the same "A label that is d..." at a 20-char cap. The position
        # prefix makes the two titles distinct by construction, so both
        # resolve now. See also the round-trip tests below, which take the
        # title straight out of the rendered payload instead of asserting a
        # hand-computed string.
        def test_labels_that_would_have_collided_without_a_prefix_both_resolve
          choices = {
            "a" => "A label that is definitely one thing",
            "b" => "A label that is definitely another"
          }

          [["a", "1. A label that i..."], ["b", "2. A label that i..."]].each do |expected_key, typed|
            setup
            @app.expect :call, [:text, "response", choices, nil], [@context]
            @middleware.call(@context)

            @context.input = typed
            @app.expect :call, [:text, "response", nil, nil], [@context]
            @middleware.call(@context)

            assert_equal expected_key, @context.input
            @app.verify
          end
        end

        # Round-trip: render the actual payload, take each title exactly as
        # WhatsApp would display it, feed it back as typed input, and
        # confirm it resolves to the choice that produced it. This is the
        # loop that a renderer/mapper disagreement on numbering would break
        # silently, and it is the same "Transfer to sa..." collision from
        # a1d08a4 that the alias-only test above exercises by hand.
        def test_round_trip_button_titles_resolve_including_the_pair_that_used_to_collide
          choices = {
            "savings" => "Transfer to savings account",
            "salary" => "Transfer to salary account"
          }

          [["savings", 0], ["salary", 1]].each do |expected_key, button_index|
            setup
            @app.expect :call, [:prompt, "Pick", choices, nil], [@context]
            _, prompt, transformed, _ = @middleware.call(@context)

            rendered = FlowChat::Whatsapp::Renderer.new(prompt, choices: transformed).render
            title = rendered[2][:buttons][button_index][:title]
            assert_operator title.length, :<=, FlowChat::Whatsapp::Renderer::BUTTON_TITLE_LENGTH

            @context.input = title
            @app.expect :call, [:text, "response", nil, nil], [@context]
            @middleware.call(@context)

            assert_equal expected_key, @context.input,
              "typing the displayed title #{title.inspect} must resolve to #{expected_key.inspect}"
            @app.verify
          end
        end

        # Same loop, one rung up: more than 3 choices renders a list instead
        # of buttons, with row titles capped at 24 instead of 20.
        def test_round_trip_list_row_titles_resolve_including_the_pair_that_used_to_collide
          choices = {
            "savings" => "Transfer to savings account",
            "salary" => "Transfer to salary account"
          }.merge((3..4).to_h { |i| ["k#{i}", "Option #{i}"] })

          [["savings", 0], ["salary", 1]].each do |expected_key, row_index|
            setup
            @app.expect :call, [:prompt, "Pick", choices, nil], [@context]
            _, prompt, transformed, _ = @middleware.call(@context)

            rendered = FlowChat::Whatsapp::Renderer.new(prompt, choices: transformed).render
            title = rendered[2][:sections][0][:rows][row_index][:title]
            assert_operator title.length, :<=, FlowChat::Whatsapp::Renderer::LIST_ROW_TITLE_LENGTH

            @context.input = title
            @app.expect :call, [:text, "response", nil, nil], [@context]
            @middleware.call(@context)

            assert_equal expected_key, @context.input,
              "typing the displayed row title #{title.inspect} must resolve to #{expected_key.inspect}"
            @app.verify
          end
        end

        # The savings/salary pair is ambiguous (truncation), so the screen is
        # numbered: typing the bare position, not just the full displayed
        # title, must also resolve.
        def test_typed_position_resolves_on_an_ambiguous_button_rung
          choices = {
            "savings" => "Transfer to savings account",
            "salary" => "Transfer to salary account"
          }
          @app.expect :call, [:text, "response", choices, nil], [@context]
          @middleware.call(@context)

          @context.input = "2"
          @app.expect :call, [:text, "response", nil, nil], [@context]
          @middleware.call(@context)

          assert_equal "salary", @context.input
          @app.verify
        end

        # The duplicate-label case: no truncation is involved at all - both
        # labels are "Accept", well under the 20-char button cap - but
        # sharing a label is exactly as ambiguous as a truncation collision,
        # so FlowChat::ChoiceTitles prefixes the whole set. Without the
        # duplicate trigger this would render two identical "Accept" buttons
        # whose aliases collide, silently resolving to whichever choice's
        # alias happened to be written last.
        def test_round_trip_duplicate_labels_each_resolve_to_their_own_distinct_key
          choices = {"yes" => "Accept", "no" => "Accept"}

          [["yes", 0], ["no", 1]].each do |expected_key, button_index|
            setup
            @app.expect :call, [:prompt, "Pick", choices, nil], [@context]
            _, prompt, transformed, _ = @middleware.call(@context)

            rendered = FlowChat::Whatsapp::Renderer.new(prompt, choices: transformed).render
            title = rendered[2][:buttons][button_index][:title]
            assert_equal "#{button_index + 1}. Accept", title, "the screen must be numbered when labels are duplicated"

            @context.input = title
            @app.expect :call, [:text, "response", nil, nil], [@context]
            @middleware.call(@context)

            assert_equal expected_key, @context.input,
              "typing the displayed title #{title.inspect} must resolve to its own choice, not the other \"Accept\""
            @app.verify
          end
        end

        # Contrast with the ambiguous cases above: "Alpha" and "Beta" are
        # short and distinct, so the screen is not numbered at all. The
        # displayed title still round-trips (it resolves via the id map,
        # since the bare title equals the choice's own generated id here),
        # but a typed bare digit is free text - no number was ever shown, so
        # there is nothing for it to be a position of.
        def test_round_trip_unambiguous_button_rung_has_no_position
          choices = {"a" => "Alpha", "b" => "Beta"}
          @app.expect :call, [:prompt, "Pick", choices, nil], [@context]
          _, prompt, transformed, _ = @middleware.call(@context)

          rendered = FlowChat::Whatsapp::Renderer.new(prompt, choices: transformed).render
          title = rendered[2][:buttons][1][:title]
          assert_equal "Beta", title, "an unambiguous title is not prefixed"

          @context.input = title
          @app.expect :call, [:text, "response", nil, nil], [@context]
          @middleware.call(@context)
          assert_equal "b", @context.input, "the displayed title must still round-trip"

          setup
          @app.expect :call, [:prompt, "Pick", choices, nil], [@context]
          @middleware.call(@context)

          @context.input = "1"
          @app.expect :call, [:text, "response", nil, nil], [@context]
          @middleware.call(@context)
          assert_equal "1", @context.input,
            "no number was shown, so a typed digit must stay free text, not resolve to a position"
          @app.verify
        end

        # On the numbered rung (above 10 choices) there is no separate title
        # to alias, only the position printed in the body; the round trip
        # there is pulling that number back out of the rendered body, exactly
        # as a user reading it would, and typing it back.
        def test_round_trip_numbered_body_position_resolves
          choices = (1..11).to_h { |i| ["key#{i}", "Option #{i}"] }
          @app.expect :call, [:prompt, "Pick", choices, nil], [@context]

          _, prompt, transformed, _ = @middleware.call(@context)

          rendered = FlowChat::Whatsapp::Renderer.new(prompt, choices: transformed).render
          third_numbered_line = rendered[1].lines.grep(/^\d+\. /)[2]
          typed_position = third_numbered_line[/^\d+/]

          @context.input = typed_position
          @app.expect :call, [:text, "response", nil, nil], [@context]
          @middleware.call(@context)

          assert_equal "key3", @context.input
          @app.verify
        end

        # Mirrors test_stale_position_map_does_not_hijack_a_later_free_text_digit:
        # resolving the alias rewrites @context.input to the choice key, which
        # no longer matches any stored map, so clear_mappings_if_needed clears
        # everything (including the alias map) before the next turn.
        def test_stale_alias_map_does_not_hijack_a_later_free_text_reply
          long_label = "A label that is definitely longer than twenty chars"
          choices = {"a" => long_label, "b" => "Beta"}
          @app.expect :call, [:text, "response", choices, nil], [@context]
          @middleware.call(@context)

          @context.input = "1. A label that i..."
          @app.expect :call, [:text, "response", nil, nil], [@context]
          @middleware.call(@context)

          assert_equal "a", @context.input

          @context.input = "1. A label that i..."
          @app.expect :call, [:prompt, "How many bags?", nil, nil], [@context]
          @middleware.call(@context)

          assert_equal "1. A label that i...", @context.input,
            "a stale alias mapping must not rewrite free text on a later screen"
          @app.verify
        end

        # A title and a position can name the same string: a choice labelled
        # "1" has the title "1", which is also the first position. The title
        # must win, or that choice could never be picked.
        def test_titles_win_over_positions
          @session.set("whatsapp.choice_mapping", {"tied" => "from_title"})
          @session.set("whatsapp.position_mapping", {"tied" => "from_position"})
          @context.input = "tied"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "from_title", @context.input
          @app.verify
        end

        # create_id_mapping only runs when the next screen has choices. A screen
        # with none (a plain prompt.ask) never touches the position map, so a
        # position map left over from an earlier numbered rung must be cleared
        # the moment it is consumed, not left to hijack a later free-text digit.
        def test_stale_position_map_does_not_hijack_a_later_free_text_digit
          choices = (1..25).to_h { |i| ["key#{i}", "Option #{i}"] }
          @app.expect :call, [:text, "response", choices, nil], [@context]

          @middleware.call(@context)

          @context.input = "3"
          @app.expect :call, [:text, "response", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "key3", @context.input

          @context.input = "3"
          @app.expect :call, [:prompt, "How many bags?", nil, nil], [@context]

          @middleware.call(@context)

          assert_equal "3", @context.input,
            "a typed digit on a screen with no choices must stay the digit, " \
            "but a stale position map rewrote it to #{@context.input.inspect}"
          @app.verify
        end

        # Mock classes for testing
        class MockSession
          def initialize
            @data = {}
          end

          def get(key)
            @data[key]
          end

          def set(key, value)
            @data[key] = value
          end

          def delete(key)
            @data.delete(key)
          end
        end

        class MockContext
          attr_accessor :input
          attr_reader :session

          def initialize(session)
            @session = session
            @data = {}
            @input = nil
          end

          def [](key)
            @data[key]
          end

          def []=(key, value)
            @data[key] = value
          end
        end
      end
    end
  end
end
